### ISSUE TITLE
Remove support for 2.7

### ISSUE THREAD

**Issue by benlower** [Kinect/PyKinect2#19]
This is all new so we are standardizing on 3.4+

**Comment by paulmelnikow** [comment]
Hey, just a plug here to please keep support for 2.7. At Body Labs we haven't ported our internal code to Python 3, and I'm not sure the status of our dependencies. Basically, without Python 2 support, it'd be a lot harder to use this for prototypes / experiments. I think this is true of our friends at MPI too; @eerac, do you know?

**Comment by benlower** [comment]
Ok good to know

-----Original Message-----

**Comment by ilanbiala** [comment]
@benlower any progress on moving to 3.4+?
