### ISSUE TITLE
Joints coordinates

### ISSUE THREAD

**Issue by arnoldad0423** [Kinect/PyKinect2#28]
First of all, thanks for the code. I am using your code, and I am just wondering whether I can retrieve each joint coordinate (maybe like in x and y values, or x, y, and z values).

Big thanks in advance. Looking forward for any response.

**Comment by karansaxena** [comment]
Use this:
print joint_points[PyKinectV2.JointType_FootLeft].x , joint_points[PyKinectV2.JointType_FootLeft].y

BTW, could you manage to figure out anything more?
I am looking for a way to extract depth field as well. Any pointers?
Thanks.

**Comment by karansaxena** [comment]
@arnoldad0423 , were you able to get the Z coordinate? I had no success.

**Comment by vladkol** [comment]
Duplicate #31
