### ISSUE TITLE
Anyone else facing this issue?

### ISSUE THREAD

**Issue by karansaxena** [Kinect/PyKinect2#30]
AttributeError: 'PyKinectRuntime' object has no attribute 'infrared_frame_desc'

**Comment by gdauphin** [comment]
Same problem here :( . I also just tried a simple code to check "self._kinect.has_new_infrared_frame()" and always get false.
Works perfectly with depth and color but not with infrared.

And 'infrared_frame_desc' is in pykinectruntime.py ...

**Comment by nseymoursmith** [comment]
I had this problem and fixed it by replacing the library files with the latest directly from this repo.

In my installation they were located at 
> anaconda3/lib/site-packages/pykinect2
Or somesuch similar place. You can find it by going into interactive mode and typing 
> import pykinect2
> help(pykinect2)

**Comment by gdauphin** [comment]
It works perfectly ! Thank you for the tip :)

**Comment by karansaxena** [comment]
@nseymoursmith This worked! Thanks!

**Comment by nmadapan** [comment]
Thank you. It works..

**Comment by hayatkhan8660-maker** [comment]
> I had this problem and fixed it by replacing the library files with the latest directly from this repo.
> 
> In my installation they were located at
> 
> > anaconda3/lib/site-packages/pykinect2
> 
> Or somesuch similar place. You can find it by going into interactive mode and typing
> 
> > import pykinect2
> > help(pykinect2)

Thanks buddy, it Works!
