### ISSUE TITLE
Z coordinate of joints.

### ISSUE THREAD

**Issue by karansaxena** [Kinect/PyKinect2#31]
Can someone please point me in the right direction to get the Z coordinate of a joint?
Is that possible?

**Comment by vladkol** [comment]
You need to get z from depth frame using x and y you got from body_joints_to_depth_space

**Comment by karansaxena** [comment]
@vladkol 
Thanks a lot. I get it now.
Sorry for spamming you everywhere I could. This was kinda urgent.

**Comment by mouarcher** [comment]
@vladkol 
https://i.stack.imgur.com/xtcnF.png
how to deal with this problem, i still cant get z coordinate
