### ISSUE TITLE
[Question]Linux ?

### ISSUE THREAD

**Issue by pranali3215** [Kinect/PyKinect2#35]
The README states that "Kinect for Windows SDK v2" is one of the dependencies. Does this mean that this does not work with Ubuntu 14.04 OS ?

**Comment by gblikas** [comment]
@pranali3215 Most likely, especially since you can only use the "Ofiicial" Kinect SDK on Windows. There are other options like ROS, and MATLAB, however.

**Comment by vladkol** [comment]
This library is basically a wrapper for Kinect for Windows SDK. Moreover, it's designed in a way Kinect SDK works (not quite a "Python way"). All contributions are welcome!
