### ISSUE TITLE
Mapper.MapColorFrameToCameraSpace 'The parameter is incorrect'

### ISSUE THREAD

**Issue by gavinwangxin** [Kinect/PyKinect2#39]
`depthframe = self._kinect.get_last_depth_frame()`
`ptr_depth = np.ctypeslib.as_ctypes(depthframe.flatten())`
`L = depthframe.size`
`TYPE_CameraSpacePointArray = PyKinectV2._CameraSpacePoint * L`
`csps1 = TYPE_CameraSpacePointArray()`
`error_state = self._kinect._mapper.MapColorFrameToCameraSpace(L, ptr_depth, L, csps1)`

It doesn't work. 

solved.....
Eh.... My bad. The size of cameraspacepoints should be equal to the color frame size.

`S = 1080*1920`
`TYPE_CameraSpacePointArray = PyKinectV2._CameraSpacePoint * S`
`csps1 = TYPE_CameraSpacePointArray()`
`error_state = self._kinect._mapper.MapColorFrameToCameraSpace(L, ptr_depth, S, csps1)`

**Comment by muharremmandaci** [comment]
depthframe = kinect.get_last_depth_frame()
    ptr_depth = numpy.ctypeslib.as_ctypes(depthframe.flatten())
    L = kinect._depth_frame_data_capacity.value

    S = 1080 * 1920
    TYPE_ColorSpacePointArray = PyKinectV2._ColorSpacePoint * S
    csps1 = TYPE_ColorSpacePointArray()

    x = kinect._mapper.MapDepthFrameToColorSpace(L, ptr_depth, S, deneme)

help. same error
