### ISSUE TITLE
unknown encoding

### ISSUE THREAD

**Issue by aegorfk** [Kinect/PyKinect2#57]
Whole running import lines right after installation:
```
from pykinect2 import PyKinectV2
from pykinect2.PyKinectV2 import *
from pykinect2 import PyKinectRuntime
```

I got:
  File "<string>", line unknown
SyntaxError: unknown encoding for '....../lib/python3.5/site-packages/pykinect2/PyKinectV2.py': mbcs

I tried even manually rewrite the file, but did not help. Any ideas?

**Comment by aegorfk** [comment]
Actually, it happened because this package is so Windows-based systems, not Unix. 
I understood.
Solved

**Comment by navinthenapster** [comment]
how can I make it available for Linux based systems. Any idea

**Comment by aegorfk** [comment]
@navinthenapster I used pylibfreenect2 package for Mac integration.
You can see it here: https://github.com/aegorfk/Mask_RCNN/blob/master/Kinect_streaming_segmentation.ipynb
