### ISSUE TITLE
Import issue with PyKinectV2

### ISSUE THREAD

**Issue by JulieFournier** [Kinect/PyKinect2#95]
Hello,
I can not import the PyKinectV2 on Python.
When using the command
from pykinect2 import PyKinectV2

I get the error:

  File "C:\Users\jufourni\Anaconda3\lib\site-packages\pykinect2\PyKinectV2.py", line 2216, in <module>
    assert sizeof(tagSTATSTG) == 72, sizeof(tagSTATSTG)

AssertionError: 80

Does anyone already have this problem and knows how to fix it ?

**Comment by KonstantinosAng** [comment]
https://github.com/Kinect/PyKinect2/issues/37

**Comment by JulieFournier** [comment]
Thank you, I hadn't seen this post.
